function format_axis_ROC
% Format the axis appropriate for plotting ROC curves

set(gca,'Clipping','off')

xlabel('False alarm rate')
ylabel('Hit rate')

% Axis properties
set(gca, ...
	'XLim',[0 1],...
	'YLim',[0 1],...
	'Box'         , 'on'     , ...
	'TickDir'     , 'out'     , ...
	'TickLength'  , [.02 .02] , ...
	'XMinorTick'  , 'off'      , ...
	'YMinorTick'  , 'off'      , ...
	'XTick'       , 0:0.25:1	, ...
	'YTick'       , 0:0.25:1	, ...
	'PlotBoxAspectRatio', [1 1 1],...
	'FontSize' , 14 );

%set(gca,'Layer','top')

grid off
box off